on:
  push:
    branches:
      - main

name: Release on NPM
jobs:
  build:
    name: release
    runs-on: ubuntu-latest
    steps:
      # Setup
      - uses: actions/checkout@master
      - uses: actions/setup-node@v2
        with:
          node-version: '13.x'
      - run: yarn install
      # Publish
      - run: yarn build
      - run: yarn test
        env:
          GH_TOKEN: ${{ secrets.GH_SPONSORS_TOKEN }}
      - run: yarn coverage
      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
